### ISSUE TITLE
Is contribution welcome ?

### ISSUE THREAD

**Issue by eljoth** [samsarahq/thunder#449]
Is this project open for contribution or is it dead ?

**Comment by amonks** [comment]
> is it dead?

Definitely not! We (at Samsara) still develop Thunder [pretty actively](https://github.com/samsarahq/thunder/graphs/contributors), and will to continue to do so.

> is this project open for contribution?

We've accepted PRs from outside contributors from time to time, but our attention is guided by our own internal needs and we tend not to allocate much time to community stewardship.

**Comment by eljoth** [comment]
Alright, I am asking because the last [release ](https://github.com/samsarahq/thunder/releases/tag/v0.5.0 )is quite some time ago now.

**Comment by amonks** [comment]
Oh! Thanks for the note. I'll see if I can push a tag.

**Comment by carwyn** [comment]
Are Samsara tracking master HEAD for production use or do you have internal tagging for stable releases? I ask as I'm not sure if we should expect master HEAD to be stable or if we are better sticking to tagged releases?

With Go module mode the default in Go 1.16 and due to be the only mode from 1.17 the occasional tag update would be much appreciated :)

**Comment by amonks** [comment]
@carwyn 
Samsara uses thunder off HEAD, internally, so that should be stable.

@eljoth
It looks like we've usually published a changelog with new tags, which seems like a good practice, but there have been many changes since our last tag, so this will take some time to put together. I haven't forgotten about this, but I can't promise I'll get it done soon. In the meantime, I'd advocate for pinning to HEAD or a recent commit.
