### ISSUE TITLE
MaxSubscriptions and MinRerunInterval

### ISSUE THREAD

**Issue by jetever** [samsarahq/thunder#98]
hello, In thunder's server.go code,
Const (
MaxSubscriptions = 200
MinRerunInterval = 1 * time.Second 
)
The default setting MaxSubscriptions=200 and MinRerunInterval=5 second is a test value, or a parameter that is recommended for use in a production system? For real-time system services, the interval of 5 seconds will be longer. If we use the interval of 1 second, what will happen? In addition, MaxSubscriptions=200 is smaller for our users. If we set larger numbers, it should be The number of? ,Thank you.

**Comment by stephen** [comment]
Support for changing these values was added in https://github.com/samsarahq/thunder/pull/112.

You can/should set these based on your needs (i.e. cpu/memory constraints on your server). Using 1 second simply means that recomputations are gated to 1 second instead of 5. Allowing more subscriptions may consume more memory per connection. Note that the max subscriptions is per client/connection, not global. This would mean that a single client can request up to 200 subscriptions, which seems quite a lot for one page.

**Comment by jetever** [comment]
Thanks very much!
